spring:
  profiles:
    default: local

  datasource:
    #url: jdbc:h2:~/reservetable
    url: jdbc:h2:tcp://localhost/~/reservetable;NON_KEYWORDS=USER
    #url: jdbc:h2:mem:~/reservetable;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: never

  h2:
    console:
      enabled: true
---

logging:
  level:
    #org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace  # 파라미터바인딩 표시


springdoc:
  #packages-to-scan: my.reservetable.controllers
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true  # 기본 url 비활성화
    display-request-duration: true      # swagger-ui에서 try 했을 때 request duration을 알려주는 설정
    tags-sorter: alpha   # 태그 정렬 순서 (알파벳 순)
    operations-sorter: method   #컨트롤러 정렬 순서
  api-docs:
    path: /api-docs   # openAPI 접근 경로

security:
  jwt:
    secret-key: $2a$10$ubAW8wgtddxdQ1p0g0ZbquNgqhRymtknL2pbpRqv/QhALnaFacJ621096
    access-expired-time: 1000 * 60 * 60 * 24 * 7 #일주일
    #access-expired-time: 15552000000   # 1시간(ms) TODO 임시로 180일 설정
    refresh-expired-time: 36000000     # 8시간(ms) => 604800000 : 7일(ms) / 10시간 => 36000000로 변경
    #cookie-max-age: 7                  # 7일(d)
